language: cpp
sudo: required
dist: trusty
notifications:
  email: false
matrix:
  include:
  - os: linux
    compiler: gcc
    env:
    - CXX_COMPILER=g++-5
    - C_COMPILER=gcc-5
    - QT_VERSION="-5.10.1"
    - QT_PKG=510
    - DEPLOYMENT=1
    - USE_BUNDLED_BOOST=1
    - USE_BUNDLED_SPDLOG=1
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - ninja-build
before_install:
  - export CXX=${CXX_COMPILER}
  - export CC=${C_COMPILER}
install:
  - echo '|1|YTXcI9F2+bVFKIz6sren2fg+Pwo=|00A151UHFKKbcNs66zsNTP/dfSQ= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKt/a6oi8ONIPVoBoBdxmnMDyE1G2HRacaEnLKoL21HzWjSzak5urj4t2qayErdI7OnPUPqMH0bbIEONK9lKkJo=' >> $HOME/.ssh/known_hosts
  - "./.ci/install.sh"
  - export PATH=/usr/local/bin:${PATH}
script:
  - "./.ci/script.sh"
  - sed -i -e "s/VERSION_NAME_VALUE/${TRAVIS_TAG}/g" ./.ci/bintray-release.json || true
  - cp ./.ci/bintray-release.json .

before_deploy:
  - openssl aes-256-cbc -K $encrypted_f98da79ae277_key -iv $encrypted_f98da79ae277_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
    provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ travis@kolab.schnuffle.de:~/
    overwrite: true
    on:
      condition: "$DEPLOYMENT == 1"
      tags: true
